### ISSUE TITLE
Prefix "Block Lab" functions with the "blocklab_" to avoid fatal errors.

### ISSUE THREAD

**Issue by camya** [getblocklab/block-lab#219]
**Problem:**
Many of "Gutenberg Block" related plugins are using the generic "block_" prefix for their function names. This could become a problem rapidly with fatal errors because of re-declared function names.
The function names like block_value(), block_field(), block_config() are too generic.

**Suggestion:**
Please prefix all "Block Lab" functions consistently with the "blocklab_".

Examples: 

- Replace `block_value()` with `blocklab_value()`
- Replace `block_config()` with `blocklab_config()`
- Replace `block_field()` with `blocklab_field()`
- ...

**Comment by lukecarbis** [comment]
I understand the concern. If there's another plugin that becomes very popular that does this, we'll implement a safeguard, but for now we'll leave them as is for two reasons: 
1. Simplicity
2. It would break existing sites

ACF uses `get_field`, and gets away with it because it's so ubiquitous. Our goal is to be just as well known!
