### ISSUE TITLE
Additional CSS Class

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#236]
The WordPress editor natively includes a "Additional CSS Class" field in the Advanced section of every block. It should be possible to retrieve the value of this field when creating a template (using a helper function).

Possibilities include:
- A custom helper function (i.e. `block_additional_css_classes`)
- Including the CSS classes with the `block_config()` help function

Props @KillerPancakes

**Comment by davidallenlewis** [comment]
Would love it the native HTML Anchor field could be utilized as well

**Comment by lukecarbis** [comment]
@UnionDesign Not 100% sure what you mean – could you please elaborate?

**Comment by davidallenlewis** [comment]
I mean when registering a block you can configure supports anchor: true in order to get a “HTML Anchor” field in the “Advanced” tab of the Settings sidebar. Right now only the native Gutenberg “Heading” blocks use them by default. It would be nice of Block Lap blocks could use this native feature as well... so every block could have a content-managed / human-readable anchor link if you wanted to use that for a jump down link... I.e. host.com/about-us#our-team 

Of course one could just make their own HTML Anchor field in their Block fields but since Gutenberg already has a method for doing this (similar to the custom CSS class field) I figure... may as well use it.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#supports-optional

**Comment by eriktdesign** [comment]
Was surprised the custom class wasn't in the block_config() function -- that's where I assumed it would be. I'd advocate for that, as well as including block alignments in there as well. #261

**Comment by eriktdesign** [comment]
Looks fixed in 1.3.1 -- thanks!

**Comment by rikkilake** [comment]
Looking in block_config() this does not appear to be fixed in 1.3.1.

No additional classes shown. :-(

array (size=6)
   'name' => string 'card' (length=4)
   'title' => string 'Card' (length=4)
   'icon' => string 'folder' (length=6)
   'category' => string 'common' (length=6)
   'keywords' => 
      array (size=2)
          0 => string 'card' (length=4)
          1 => string 'bootstrap' (length=9)
   'fields' => 
      array (size=12)
   ...

**Comment by lukecarbis** [comment]
We didn't put it in `block_config()`. The Additional CSS classes can be access through the block slug `className`. e.g.:

```
<div class="<?php block_field( 'className' ); ?>">
    …
</div>
```

More info here: https://github.com/getblocklab/block-lab/wiki/7.-FAQ

**Comment by rikkilake** [comment]
Thank you.
