### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#25]
If `field_one` is equal to `foo` then hide `field_two`.

**Comment by finnruijter** [comment]
That would be great!

**Comment by x5hwuk7nc6jsudcc** [comment]
This would be a very useful feature as it would reduce the number of blocks required to reproduce similar design elements. 

Use case: We have an intricate design that uses two columns, with some custom icons above each column. On another page we have the same design but it uses three columns and doesn't have icons.  Having a conditional field logic would allow us to keep all of that code in a single php/css block pair instead of having a lot of duplicated code and logic for the other elements.

**Comment by lukecarbis** [comment]
Closing in favour of #278.
