### ISSUE TITLE
Get attachment ID of image

### ISSUE THREAD

**Issue by DieTapete** [getblocklab/block-lab#256]
Hey, seems like it's not possible to get the ID of an image?! I would propose something like this:
```
block_value('image') => www.wordpress.com/image.jpg
block_value('image.id') => 12
```
Alternatively we can of course just return the whole WP_Post object.
```
block_value('image')->ID => 12
```

**Comment by lukecarbis** [comment]
That's a really nice format. As we grow the types of fields we'll have a need to do something like this. Here's another approach:

```php
$format = 'default';
block_value( 'image', $format );
// returns https://domain.com/image.jpg

$format = 'id';
block_value( 'image', $format );
// returns 42

$format = 'object';
block_value( 'image', $format );
// returns an attachment WP_Post object
```

**Comment by davidallenlewis** [comment]
In ACF what gets returned is controlled by the field configuration in the Dashboard. But I actually like this better though. That way if you ever want to or need to change what gets returned as you've developing a project you can just change that second argument instead of having to redefine the field config. Then again not all field types will require that second argument (only post type fields).
