### ISSUE TITLE
Adding a function in PHP code inside template file throws fatal error

### ISSUE THREAD

**Issue by moinzaman** [getblocklab/block-lab#264]
Steps to reproduce:

1. Create a block with any field(s)
2. Create a `block-{name}.php` for block to use
3. Use this block in a page or a post and save.
4. Put any function in a php block in the template file. Like this:
```
<?php
function foo() {
    return true;
}
?>
```
5. Now navigate to edit this page from `wp-admin`
6. See fatal error like so:
![image](https://user-images.githubusercontent.com/505711/54889136-1a801100-4ef7-11e9-9445-142a40b59e19.png)

**Comment by lukecarbis** [comment]
This is simply because the template needs to be loaded more than once, so the function you're writing is redeclared, causing the fatal error.

I'd recommend putting these sort of functions in your theme's `functions.php` file, or in a plugin, not in the template itself.

I can't imagine a good reason for putting a function in a template, but if there is one, simply wrap it in a `function_exists()` check to avoid the error:
```
if ( ! function_exists( 'foo' ) {
    function foo() {
        return true;
    }
}
```
