### ISSUE TITLE
Range field type does not allow "0" as a value

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#333]
This seems to be a bug.  I have a Range field type, which should allow a range of 0 to 100.  However editors are unable to enter the value "0".

When I allow the range of -1 to 100, editors are still unable to use the value "0" (although can select "-1").

**Comment by lukecarbis** [comment]
Can confirm this bug. I believe that the problem is caused by the fact that the "minimum" setting for the field doesn't save if the value is set to 0.

![2019-06-11 09-50-31 2019-06-11 09_53_04](https://user-images.githubusercontent.com/1097667/59234125-b97ef400-8c2e-11e9-8476-31c0c3ccf79f.gif)

![Screen Shot 2019-06-11 at 9 51 34 am](https://user-images.githubusercontent.com/1097667/59234126-bb48b780-8c2e-11e9-9112-89ebe91d7ac7.png)
