### ISSUE TITLE
Second time "Add Field" does not update slug for that field when pressed CTRL+V

### ISSUE THREAD

**Issue by abillahbd** [getblocklab/block-lab#378]
Issue: When creating a block, when I click on "Add Field" button, if it's the first field, then whenever I paste something into the "Field Label" textbox, it automatically updates the "slug" for that field. But if it's the second field (second time adding a field), then pasting into the "Field Label" does not update the "slug". 

How to replicate:

Go to "add new block" page.
Click "Add field" button.
Paste something into "Field label" textbox.
Then click "Add field" button again.
Then again paste something into the second field's "Field Label" textbox.
- It won't update the slug for the second field.

Expected behavior:

Second field should update its slug just like the first field.

Thanks.

**Comment by lukecarbis** [comment]
This occurs because the field "blurs" (loses focus) when the browser window loses focus (which presumably you're doing to copy the value you need).

An easy workaround is to copy the value to your clipboard _before_ adding the new field. Like this:

![2019-08-15 08-32-43 2019-08-15 08_42_21](https://user-images.githubusercontent.com/1097667/63061532-cffc4100-bf38-11e9-97ff-f160f676da86.gif)

It is possible to fix this. It could be done in the `blur` handler, by comparing the field value to the default value (from `wp.template( 'field-repeater' )`, and if it's the same, don't turn off auto-slugging.
