### ISSUE TITLE
Legacy images not showing up anymore

### ISSUE THREAD

**Issue by gaslampmedia** [getblocklab/block-lab#512]
On the latest v1.5.2 legacy image (urls instead of ids) are not showing up anymore.

I've tried hooking into a bunch of actions and filters in the plugin, but I can't find a place to temporarily fix it. 

Here's an example of post_content that has an image that doesn't show up. I've verified that it exists in the media library too.

```html
<!-- wp:block-lab/image-left-text-right-grey {"image":"https://workforce.org/wp-content/uploads/2019/02/C2C-county-intern.jpg","title":"Connect2Careers","text-area":"16–24 years old and live in San Diego County? Connect2Careers want to help you find a job. Sign up to tap into peer support, exclusive programs, professional training and job leads you won’t find anywhere else.\n\u003cbr\u003e \n\u003ca href=\u0022/c2csd\u0022 class=\u0022btn btn-primary mt-2\u0022\u003eLearn More\u003c/a\u003e \u003ca href=\u0022https://sdwp-jobs.force.com/s/login/\u0022 class=\u0022btn btn-primary mt-2\u0022 target=\u0022_blank\u0022\u003eLog in\u003c/a\u003e"} /-->
```

When I hook into `block_lab_data` or any other filters, the attributes don't have the `image` (slug of image field) key. 

Any ideas?

**Comment by gaslampmedia** [comment]
Forgot to mention, I tried resaving the block that has the image field, but it did not work.
I've reverted back to `v1.1.3`, resaved the field, and the images are back.

I'd really like to get this updated though.

**Comment by kienstra** [comment]
Hi @gaslampmedia,
Sorry for not replying sooner. 

Assuming that this is still a problem, could you please try the following on a staging server?

1. With the Block Lab `v1.1.3` version that you mentioned, go to the 'Edit Block' UI for the block with the image, and click 'Update':

![block-im](https://user-images.githubusercontent.com/4063887/74688878-9d105f80-519e-11ea-8ea1-721a6c67f825.png)

2. Upgrade to the latest version of Block Lab, `1.5.3`.

3. Go to the front-end, and see whether the block's image renders

This worked in my local, I hope it works for you.

Otherwise, we'll keep working on this here 😄

**Comment by kienstra** [comment]
Closing now for lack of activity, but feel free to reply with more information. Sorry for my [late reply](https://github.com/getblocklab/block-lab/issues/512#issuecomment-587173481) earlier.
