### ISSUE TITLE
Support render_cllback

### ISSUE THREAD

**Issue by yaquawa** [getblocklab/block-lab#667]
Hi! Thanks for all the efforts for creating this amazing plugin! Totally game changer for creating gutenberg blocks.💖💖💖💖

## Feature description
I'm using my own theme called [laraish](https://github.com/laraish/laraish), which allow run Laravel in a regular WordPress theme. So the view part of the theme is built from blade templates. 

I want to render the blocks by using my Blade template, so I would suggest to make block-lab to accept [render_callback](https://developer.wordpress.org/reference/functions/register_block_type/) to render the blocks. 

Also by doing such a way we could organize our code more nicely rather than just put all the logics in the template php file.

Furthermore, I would expect either a class name or a function name is acceptable.

The block rendering fallback strange could be:
- if there is any matched php template just render with it.
    - Check if it is a function or class. If it is a function name, call it to render the block. If it's a class, just create an instance of it with all the meta data, and then call the `render` method of it.
        - If either of them was not provided, check if a function called `block_lab_render_callback` exists, if it is, call that function.

What do you think? Thanks!

**Comment by kienstra** [comment]
Hi @yaquawa,
Thanks for bringing this up, and for your kind words about Block Lab.

>I want to render the blocks by using my Blade template, so I would suggest to make block-lab to accept render_callback to render the blocks.

Interesting, where would Block Lab accept a `render_callback` parameter? In [block_lab_add_block()](https://getblocklab.com/docs/functions/block_lab_add_block/)?

Otherwise, would the `pre_render_block` filter be enough?

https://github.com/WordPress/wordpress-develop/blob/a5cb12dce1e812aa8ce4814cce697e611010cf55/src/wp-includes/blocks.php#L670

Thanks!

**Comment by yaquawa** [comment]
@kienstra Thanks for the information!
I didn't know the `pre_render_block` filter, best place to hook in!
